### ISSUE TITLE
Jest unit tests - SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by marocas** [s-group-dev/react-usercentrics#26]
My application codebase is in NextJs with React.
I have a component Media, that needs user consent to enable a script that collects data, so we created a hook that verifies if we can load this Media component.

I can run more atomic (atomic pattern design) unit tests without any problems, but when coming to organisms, I start getting this error.

Can you guys assist me on this?

````JAVASCRIPT
yarn run v1.22.19
$ jest --silent Hero.spec.tsx
 FAIL  src/components/organisms/Hero/__tests__/Hero.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /<APPLICATION>/node_modules/@s-group/react-usercentrics/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { UsercentricsDialogToggle } from './components/UsercentricsDialogToggle.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import {
        | ^
      2 |   getServicesBaseInfo,
      3 |   hasServiceConsent,
      4 |   ServiceInfo,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/hooks/usePermission.ts:1:1)
      at Object.<anonymous> (src/hooks/useMarketo.ts:3:1)
      at Object.<anonymous> (src/hooks/index.ts:9:1)
      at Object.<anonymous> (src/components/molecules/media/Media.tsx:4:1)
      at Object.<anonymous> (src/components/molecules/media/index.ts:1:1)
      at Object.<anonymous> (src/components/organisms/Hero/Hero.tsx:7:1)
      at Object.<anonymous> (src/components/organisms/Hero/index.ts:1:1)
      at Object.<anonymous> (src/components/organisms/Hero/__tests__/Hero.spec.tsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.356 s
error Command failed with exit code 1.
````

**Comment by iiroj** [comment]
The error message is pretty descriptive, sounds like your configuration is not supporting ESM packages natively and some transpilation is necessary!
